"""
Prompt bank for high-confidence bisimulation evaluation.
Provides 100 diverse prompts to reduce variance vs 20-prompt studies.
"""

PROMPTS_100 = [
    "The quick brown fox jumps over the lazy dog and then proceeds to",
    "In the year 2050, artificial intelligence had become so advanced that",
    "The stock market experienced significant volatility today as investors",
    "Scientists at CERN announced a breakthrough discovery in particle physics",
    "The recipe calls for two cups of flour, one egg, and a tablespoon of",
    "According to the latest research published in Nature, the human brain",
    "The president delivered a speech addressing the nation's economic concerns",
    "In a small village nestled between mountains, there lived an old",
    "The programming language Python was created by Guido van Rossum in",
    "Climate change continues to pose significant challenges for coastal cities",
    "The theory of relativity, proposed by Albert Einstein in 1905",
    "During the Renaissance period, art and science flourished across Europe",
    "The company reported quarterly earnings that exceeded analyst expectations",
    "In quantum mechanics, the uncertainty principle states that one cannot",
    "The novel begins with the protagonist waking up in an unfamiliar",
    "Recent advances in natural language processing have enabled machines to",
    "The ancient Romans built an extensive network of roads connecting",
    "Photosynthesis is the process by which plants convert sunlight into",
    "The basketball game went into overtime after a last-second three-pointer",
    "Machine learning algorithms can be broadly categorized into supervised and",
    "The spacecraft entered Mars orbit after a seven-month journey through",
    "Neuroscientists studying memory consolidation found that sleep deprivation",
    "The central bank decided to raise interest rates to combat",
    "A team of marine biologists documented unusual migration patterns in",
    "The software update introduced several performance improvements but also",
    "Shakespeare's tragedies often explore themes of ambition, betrayal, and",
    "The data center outage affected thousands of customers across multiple",
    "In game theory, a Nash equilibrium occurs when no player",
    "The startup's valuation doubled after securing funding from prominent",
    "Astronomers detected a potentially habitable exoplanet orbiting a nearby",
    "The museum's latest exhibition showcases impressionist paintings alongside",
    "When debugging distributed systems, engineers often start by tracing",
    "The electric vehicle market has grown rapidly as battery costs",
    "The cybersecurity report warned that phishing attacks have become",
    "The architect designed the building to maximize natural light while",
    "Genome sequencing technologies have dramatically reduced the cost of",
    "At the conference, researchers debated whether scaling laws imply",
    "The chef explained that caramelization occurs when sugars are heated",
    "Satellite imagery revealed that deforestation in the region had",
    "The legal brief argued that the precedent established in 1998",
    "Cloud-native applications rely on orchestration frameworks to manage",
    "The patient responded well to treatment after doctors adjusted",
    "The board of directors approved a strategic plan focused on",
    "High-frequency trading firms compete on latency measured in",
    "The documentary explores how urban planning decisions shape",
    "In linguistics, code-switching refers to alternating between languages",
    "The robotics team optimized the control policy using reinforcement",
    "A sudden drop in atmospheric pressure suggested that a storm",
    "The historian noted that primary sources from the period",
    "Open-source communities thrive when maintainers provide clear",
    "The telescope's adaptive optics system compensates for atmospheric",
    "To estimate causal effects, economists often use instrumental",
    "The pharmaceutical trial enrolled participants across twelve",
    "The glacier has retreated significantly over the past",
    "In cryptography, public-key schemes enable secure communication",
    "The city council proposed a zoning change to encourage",
    "Biochemical pathways regulating metabolism involve feedback",
    "The airline rerouted several flights due to severe",
    "The research prototype achieved state-of-the-art accuracy on",
    "Teachers reported that project-based learning improved",
    "An unexpected resonance caused the bridge to oscillate",
    "The startup pivoted from consumer software to enterprise",
    "In topology, a continuous deformation that preserves",
    "The fisheries report recommends reducing catch limits to",
    "Hardware accelerators can substantially increase throughput for",
    "The election analysis highlighted turnout differences across",
    "Ancient manuscripts preserved in dry climates often",
    "The ethics committee requested additional safeguards for",
    "A careful ablation study can isolate which component",
    "The novelist's prose balances lyrical descriptions with",
    "The anti-corruption task force uncovered evidence that",
    "Renewable energy integration requires improvements in grid",
    "In Bayesian inference, prior beliefs are updated using",
    "The startup's customer churn decreased after improving",
    "Archaeologists discovered a settlement indicating long-distance",
    "The model's calibration error increased when evaluated on",
    "Marine heatwaves can disrupt ecosystems by altering",
    "The court's majority opinion emphasized constitutional",
    "Software reliability improved after introducing property-based",
    "In epidemiology, the basic reproduction number indicates",
    "The art restoration team used spectroscopy to identify",
    "The latest compiler release reduced binary size by",
    "Researchers observed that multimodal models can benefit from",
    "The wildfire spread rapidly due to dry vegetation and",
    "A robust benchmark should include both in-distribution and",
    "The startup expanded into Latin American markets after",
    "In condensed matter physics, quasiparticles emerge from",
    "The policy memo proposes a phased rollout to minimize",
    "By analyzing user journeys, designers identified bottlenecks in",
    "The vaccine's efficacy remained high against several",
    "The autonomous drone adjusted its trajectory to avoid",
    "The committee concluded that additional evidence is needed before",
    "Economic indicators suggest consumer confidence has begun to",
    "The mathematician presented a proof that relies on",
    "The operations team reduced downtime by automating",
    "A comparative study across regions found substantial variation in",
    "The geologist explained that plate subduction can trigger",
    "The engineering team implemented circuit breakers to prevent",
    "In reinforcement learning, exploration strategies determine how",
    "The final report recommends prioritizing interventions that",
]
